export const LangStrings = {
  en: {
    email: 'E-mail',
    access: 'User',
    password: 'Password',
    forgot_password: 'Esqueci minha senha',
    forgot_password_description: 'Reset your password',
    forgot_password_title: `Reset your password`,
    forgot_button_send: 'Send',
    forgot_send: 'An email will be sent to reset the password!',
    login: 'login',
    Don_t_have_access: `Don t have access?`,
    required_email: 'Required email',
    required_access: 'Required acess',
    invalid_email: 'Invalid email',
    invalid_access: 'Invalid acess',
    required_password: 'Required password',
    email_send: 'E-mail send!',
    contact_suport_password:
      'Contact support and request to change your password!',
    keep_connected: 'Manter conectado',
  },
  pt: {
    email: 'E-mail',
    access: 'Usuário',
    password: 'Senha',
    forgot_password: 'Esqueci minha senha',
    forgot_password_description: 'Redefina sua senha',
    forgot_password_title: 'Redefina sua senha',
    forgot_button_send: 'Enviar',
    forgot_send:
      'Será enviado um o e-mail para realizar a redefinição de senha!',
    login: 'Login',
    Don_t_have_access: `Não possui acesso?`,
    required_email: 'E-mail obrigatório',
    required_access: 'Acesso obrigatório',
    invalid_email: 'E-mail inválido',
    invalid_access: 'Acesso inválido',
    required_password: 'Senha obrigatória',
    email_send: 'E-mail enviado!',
    contact_suport_password:
      'Entre em contato com o suporte e solicite a alteração de sua senha!',
    keep_connected: 'Manter conectado',
  },
};
